name: einx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test_py38:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest "jax[cpu]" flax torch tensorflow einops
    - name: Test with pytest
      run: |
        pip install .
        pytest
        EINX_CACHE_SIZE=0 pytest

  test_py310:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest "jax[cpu]" flax dm-haiku torch tensorflow einops equinox
        pip install --upgrade keras
    - name: Test with pytest
      run: |
        pip install .
        pytest
        EINX_CACHE_SIZE=0 pytest